language = "C"
include_guard = "RUST_BINDINGS_H"
includes = ["../../git-compat-util.h"]
no_includes = true
usize_is_size_t = true
style = "tag"

[export]
include = [
    "ConfigContext",
    "ConfigEvent",
    "ErrorCode",
    "KeyValueInfo",
]

[export.rename]
ConfigContext = "config_context"
ConfigEvent = "config_event"
ConfigOrigin = "config_origin"
ConfigScope = "config_scope"
ErrorCode = "err"
KeyValueInfo = "key_value_info"

[enum]
rename_variants = "ScreamingSnakeCase"
prefix_with_name = true
